services:
  db:
    container_name: postgres
    image: postgres
    environment:
      POSTGRES_USER: hexa
      POSTGRES_PASSWORD: hexa
      POSTGRES_DB: hexa
      PGDATA: /data/postgres
    volumes:
      - db:/data/postgres
    ports:
      - "5432:5432"
    networks:
      - db
    restart: unless-stopped
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -d hexa -U hexa" ]
      interval: 30s
      timeout: 10s
      retries: 5
  
  redis:
    image: redis:6.2-alpine
    restart: always
    ports:
      - '6379:6379'
    command: redis-server --save 20 1 --loglevel warning --requirepass eYVX7EwVmmxKPCDmwMtyKVge8oLd2t81
    volumes: 
      - redis:/data

networks:
  db:
    driver: bridge

volumes:
  db:
  redis:
    driver: local