services:
  db:
    container_name: postgres
    image: postgres
    environment:
      POSTGRES_USER: hexa
      POSTGRES_PASSWORD: hexa
      POSTGRES_DB: hexa
      PGDATA: /data/postgres
    volumes:
      - db:/data/postgres
    ports:
      - "5432:5432"
    networks:
      - db
    restart: unless-stopped
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -d postgres" ]
      interval: 30s
      timeout: 10s
      retries: 5
  
  keydb:
    image: eqalpha/keydb
    container_name: keydb
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - ./data:/data
      - ./keydb.conf:/etc/keydb/keydb.conf
    command: keydb-server /etc/keydb/keydb.conf --appendonly yes
    networks:
      - db
  redis:
    image: redis:6.2-alpine
    restart: always
    ports:
      - '6379:6379'
    command: redis-server --save 20 1 --loglevel warning --requirepass eYVX7EwVmmxKPCDmwMtyKVge8oLd2t81
    volumes: 
      - redis:/data

networks:
  db:
    driver: bridge

volumes:
  db:
  redis:
    driver: local